
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA DASH DOT IDENTIFIER INDEX LPAREN ON PRIMARY PROPERTY REFERENCE RPAREN TABLE UNIQUEdatabase : table_def\n| table_def databasetable_def : TABLE IDENTIFIER COLON column_defscolumn_defs : column_def\n| column_def column_defscolumn_def : DASH IDENTIFIER LPAREN properties RPARENproperties : PROPERTY\n| PROPERTY COMMA properties\n| PRIMARY\n| UNIQUE\n| REFERENCE IDENTIFIER DOT IDENTIFIER'
    
_lr_action_items = {'TABLE':([0,2,7,8,10,18,],[3,3,-3,-4,-5,-6,]),'$end':([1,2,4,7,8,10,18,],[0,-1,-2,-3,-4,-5,-6,]),'IDENTIFIER':([3,9,17,22,],[5,11,20,23,]),'COLON':([5,],[6,]),'DASH':([6,8,18,],[9,9,-6,]),'LPAREN':([11,],[12,]),'PROPERTY':([12,19,],[14,14,]),'PRIMARY':([12,19,],[15,15,]),'UNIQUE':([12,19,],[16,16,]),'REFERENCE':([12,19,],[17,17,]),'RPAREN':([13,14,15,16,21,23,],[18,-7,-9,-10,-8,-11,]),'COMMA':([14,],[19,]),'DOT':([20,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'database':([0,2,],[1,4,]),'table_def':([0,2,],[2,2,]),'column_defs':([6,8,],[7,10,]),'column_def':([6,8,],[8,8,]),'properties':([12,19,],[13,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> database","S'",1,None,None,None),
  ('database -> table_def','database',1,'p_database','dsl_parser.py',39),
  ('database -> table_def database','database',2,'p_database','dsl_parser.py',40),
  ('table_def -> TABLE IDENTIFIER COLON column_defs','table_def',4,'p_table_def','dsl_parser.py',44),
  ('column_defs -> column_def','column_defs',1,'p_column_defs','dsl_parser.py',48),
  ('column_defs -> column_def column_defs','column_defs',2,'p_column_defs','dsl_parser.py',49),
  ('column_def -> DASH IDENTIFIER LPAREN properties RPAREN','column_def',5,'p_column_def','dsl_parser.py',53),
  ('properties -> PROPERTY','properties',1,'p_properties','dsl_parser.py',57),
  ('properties -> PROPERTY COMMA properties','properties',3,'p_properties','dsl_parser.py',58),
  ('properties -> PRIMARY','properties',1,'p_properties','dsl_parser.py',59),
  ('properties -> UNIQUE','properties',1,'p_properties','dsl_parser.py',60),
  ('properties -> REFERENCE IDENTIFIER DOT IDENTIFIER','properties',4,'p_properties','dsl_parser.py',61),
]
